service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  timeout: 30
  memorySize: 2048
plugins:
 - serverless-offline
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
