on:
  push:
    branches: 
      - master
jobs: 
  build-deploy:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version : ${{matrix.node-version}}
      - run: cd ./directory && npm install
      - name: serverless deploy
        uses: serverless/github-action@master
        with: 
          args: -c "cd ./directory && serverless deploy"
          entryPoint: /bin/sh
        env: 
          AWS_ACCESS_KEY_ID: AKIA36UHBMUYRN3RQXPG
          AWS_SECRET_ACCCESS_KEY: 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